#!/usr/bin/python2.7

'''
MySQL Analysis Tool

MAT is a simple tool that created by Python language which used to analyze Mysql directory files. It is able to create image file for entire Mysql directory and analyze the log files from the image. This tool provides fastest and easiest way to analyze Mysql database to find out which data had been modified, inserted or deleted after an attack.

This tool is a prototype, may contain several bugs and lack of features. 

Contributed by Anson Tan
'''

import os
import sys
import fileinput
import hashlib

#command list
def man():
	print '\nMySQL Analysis tool command list and description\n'
	print '-----------------------------------------------------'
	print '        Command		|         Description'
	print '-----------------------------------------------------'
	print 'detect mysql		| detect MySQL directory in operating system'
	print 'show binary		| show binary file'
	print 'show log		| show log files'
	print 'show history		| show mysql history'
	print 'show error		| show error log'
	print 'show query		| show general query file'
	print 'analyze binary		| analyze binary file, such as analyze binary mysql000.000'
	print 'create mysql		| create mysql image file'
	print 'mount mysql.iso		| mount an image file called mysql.iso'
	print 'unmount mysql.iso	| unmount an image file called mysql.iso'
	print 'num state		| highest number of insert/delete/update statements'
	print 'save output		| save previous output'
	print 'hash mysql.iso		| calculate hash number for mysql.iso'
	print 'version			| show tool version'
	print 'clear			| clear screen'
	print '-----------------------------------------------------'
	print '        Command		|      shortcut command'
	print '-----------------------------------------------------'
	print 'detect mysql		| det mysql'
	print 'show binary		| s binary, s bin'
	print 'show log		| s log'
	print 'show history		| s history, s his'
	print 'show error		| s error, s err'
	print 'show query		| s query, s que'
	print 'analyze binary		| ana bin, an bin'
	print 'create mysql		| c mysql'
	print 'mount mysql.iso		| m mysql.iso'
	print 'unmount mysql.iso	| un mysql.iso'
	print 'save output		| save out'
	print 'hash mysql.iso		| h mysql.iso'
	forensic(result)
		
#command line
def forensic(result):

	output = ""
	#input command line
	option = raw_input("\nmat > ")

	#show binary file	
	if option == 'show binary' or option == 's binary' or option == 's bin':
		#Accept binary file name from user input
		binaryfile = raw_input('\nEnter binary file name: ')
		#Read binary file
		os.system('mysqlbinlog ~/Downloads/mysql-iso/' + binaryfile)
		result = 'mysqlbinlog ~/Downloads/mysql-iso/' + binaryfile
		forensic(result)

	#show log files
	elif option == 'show log' or option == 's log':

		os.system("ls -la ~/Downloads/mysql-iso")
		result = 'ls -la ~/Downloads/mysql-iso'
		forensic(result)

	#show mysql history
	elif option == 'show history' or option == 's history' or option == 's his':

		os.system('cat /home/wk/.mysql_history')
		result = 'cat /home/wk/.mysql_history'
		forensic(result)

	#show error log
	elif option == 'show error' or option == 's error' or option == 's err':

		print '\nError Log\n'
		os.system('cat ~/Downloads/mysql-iso/error.log')
		result = 'cat ~/Downloads/mysql-iso/error.log'
		forensic(result)

	#detect mysql directory
	elif option == 'detect mysql' or option == 'det mysql':

		os.system('ls -l /var/log/mysql')
		result = 'ls -l /var/log/mysql'
		forensic(result)

	#show general query file
	elif option == 'show query' or option == 's query' or option == 's que':

		print '\nGeneral Query Log\n'
		os.system('cat ~/Downloads/mysql-iso/mysql.log')
		result = 'cat ~/Downloads/mysql-iso/mysql.log'
		forensic(result)

	#create mysql image file
	elif option == 'create mysql' or option == 'c mysql':

		con = raw_input("May takes a while to backup, type 'Y' to proceed or 'R' to return : ")
		if con == 'Y' or con == 'Yes':
			os.system('sudo mkisofs -o ~/Downloads/mysql.iso /var/lib/mysql')
			print hashlib.md5(open('/home/wk/Downloads/mysql.iso', 'rb').read()).hexdigest()
			print '\n'
		
		########### calculate Hash value after created image

		elif con == 'R':
			forensic(result)
		else:
			print 'Invalid option'
			forensic(result)

	#mount mysql image file
		######### Calculate hash value before mount image
	elif option == 'mount mysql.iso' or option == 'm mysql.iso':

		os.system('sudo mkdir ~/Downloads/mysql-iso')
		os.system('sudo mount -o loop ~/Downloads/mysql.iso ~/Downloads/mysql-iso')
		print hashlib.md5(open('/home/wk/Downloads/mysql.iso', 'rb').read()).hexdigest()
		forensic(result)

	#calculate hash for Mysql image file using MD5
	elif option == 'hash mysql.iso' or option == 'h mysql.iso':

		print hashlib.md5(open('/home/wk/Downloads/mysql.iso', 'rb').read()).hexdigest()
		forensic(result)

	#unmount mysql image flle
	elif option == 'unmount mysql.iso' or option == 'un mysql.iso':

		os.system('sudo umount ~/Downloads/mysql-iso')
		#successed then print, 2>
		print 'ISO is successfully unmounted'
		forensic(result)

	#analyze binary file
	elif option == 'analyze binary' or option == 'ana bin' or option == 'an bin':

		#Accept binary file name
		filename = raw_input('Please input file name : ')
		#Open sum.sh but read only
		f1 = open('/usr/bin/sum.sh', 'r')
		#Open analyze.sh but write only
		f2 = open('/usr/bin/analyze.sh', 'w')
		for line in f1:
			#Copy all lines from sum.sh and replace user input into analyze.sh
			f2.write(line.replace('logfile', filename))
		f1.close()
		f2.close()
		#Execute analyze.sh
		os.system('. /usr/bin/analyze.sh')
		result = '. /usr/bin/analyze.sh'
		forensic(result)

	#highest number of insert/delete/update statements
	elif option == 'num state':

		#Accept binary file name
		filename = raw_input('Please input file name : ')
		#Open sum.sh but read only
		f1 = open('/usr/bin/sum.sh', 'r')
		#Open analyze.sh but write only
		f2 = open('/usr/bin/analyze.sh', 'w')
		for line in f1:
			#Copy all lines from sum.sh and replace user input into analyze.sh
			f2.write(line.replace('logfile', filename))
		f1.close()
		f2.close()
		#Execute analyze.sh
		os.system(". /usr/bin/analyze.sh | grep DELETE |cut -d':' -f2 | sort | uniq -c | sort -nr")
		print '\n'
		os.system(". /usr/bin/analyze.sh | grep INSERT |cut -d':' -f2 | sort | uniq -c | sort -nr")
		print '\n'
		os.system(". /usr/bin/analyze.sh | grep UPDATE |cut -d':' -f2 | sort | uniq -c | sort -nr")
		forensic(result)

	
	############ restore mysql file?

	#mat command list and description
	elif option == 'man':

		man()
	
	#clear screen
	elif option == 'clear' or option == 'cl':

		os.system('clear')
		forensic(result)

	elif option == 'version':

		print 'MySQL Analysis Tool v1.3, contributed by Anson Tan'
		forensic(result)

	#exit program
	elif option == 'exit':

		sys.exit(1)



	#save output for binary file
	elif option == 'save output' or option == 'save out':
		#input filename for binary file output
		filename = raw_input("Please enter filename for the output > ")
		os.system(result + '>' + filename + '.txt')
		print filename + ' is successfully saved'
		forensic(result)
	#return to forensic function after accepted invalid input
	else:

		print 'Invalid option'
		forensic(result)
		
#Display menu options
#Menu options
print '***********************************'
print '*                MAT              *'
print '*     MYSQL Analysis Tool v1.3    *'
print '***********************************'

result = ""
forensic(result)
